### ISSUE TITLE
Can't set custom avatar or favicon

### ISSUE THREAD

**Issue by Harrtron** [laozhu/hugo-nuo#121]
Great theme, but seems I cannot use a custom avatar.

Well, I can, if I overwrite the avatar.png in the theme directory. But I want to hook up the theme as a git submodule rather than just cloning it, so it can be kept up to date. 

Seems to be hard coded into the theme to use the avatar (and probably more) from the themes own directory.

**Comment by laozhu** [comment]
Hi, @Harrtron 
Sorry for the later reply,  #119  should be what you want.

**Comment by mbrukman** [comment]
@laozhu -- would it make sense to add the content of [your comment][comment-howto] to the top-level `README.md` file so that it's clear how to do this?

I basically guessed that this would work (because my understanding is that any file in a Hugo template can be overridden in Hugo by creating a new file with the same path + same name in the repo) and so I did it that way, and it worked for me, but may be non-obvious to folks new to Hugo.

[comment-howto]: https://github.com/laozhu/hugo-nuo/issues/119#issuecomment-482632971

**Comment by laozhu** [comment]
@mbrukman Thank you for your nice advice, I have updated README's [Custom theme](https://github.com/laozhu/hugo-nuo#custom-theme) section.
