### ISSUE TITLE
Add Subtitle to Post

### ISSUE THREAD

**Issue by wenbo5565** [laozhu/hugo-nuo#54]
Hi, I was trying to add a subtitle in YAML front to my post (.Rmd) file. However, I cannot get a subtitle shown on my webpage even the YAML front contains subtitle. I use R Blogdown package to build the post. People from R Blogdown told me this was because the Hugo theme I was using doesn't support subtitle. Can I get any idea on how to get a subtitle?Thank you.

![image](https://user-images.githubusercontent.com/7663395/35640961-bd0d8b14-068c-11e8-8982-15d2abece0a2.png)

![image](https://user-images.githubusercontent.com/7663395/35641013-e8151eb2-068c-11e8-9bcc-835db657e43d.png)

**Comment by YonghuiDong** [comment]
This theme supports subtitle for the webpage, but not the posts.

You need to modify the css file yourself. However, this theme is not fully compatible with blogdown, You can refer to another issue #45, which is also related to the theme customization using blowdown.

Unlike blowdown, after theme customization you need to run sass to regenerate the static folder in order to make it function.

I hope it will help.

**Comment by wenbo5565** [comment]
Sorry for my very delayed response. Thank you for the info and I will look into it.
