### ISSUE TITLE
使用中文tags报错

### ISSUE THREAD

**Issue by buyaoshushu** [laozhu/hugo-nuo#69]
Error while rendering "page" in "post/": template: /home/kerwin/git/buyaoshushu/themes/hugo-nuo/layouts/post/single.html:12:32: executing "main" at <.Params.tags>: range can't iterate over 游戏

**Comment by laozhu** [comment]
[The error line below](https://github.com/laozhu/hugo-nuo/blob/d3980b72a54fa4b335a677cc6bceb8f62659f019/layouts/post/single.html#L13) in `single.html` template maybe have problem with function urlize.

```html
{{ range $tag := .Params.tags }}
  <li>
    <a href="/tags/{{ $tag | urlize }}">
      <span class="tag">{{ $tag | title }}</span>
    </a>
  </li>
{{ end }}
```

I can't figure out what your problem is, you can read the [official docs of urlize](https://gohugo.io/functions/urlize/) and try to find the answer.

**Comment by buyaoshushu** [comment]
Thx.I include the markdown from jekyll.this type of  is not support in hugo,
```
---
tags: 日记
---
```
It has to be a array like 
```
---
tags: [日记]
---
```
